apiVersion: apps/v1
kind: Deployment
metadata:
  name: corecontrast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corecontrast
  template:
    metadata:
      labels:
        app: corecontrast
    spec:
      containers:
      - name: corecontrast
        image: docker.io/adiprerepa/corecontrast-singlecore:latest
        ports:
        - containerPort: 8080
        env:
        - name: GIN_MODE
          value: "release"
---
apiVersion: v1
kind: Service
metadata:
  name: corecontrast
spec:
  selector:
    app: corecontrast
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
