apiVersion: apps/v1
kind: Deployment
metadata:
  name: record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: record-service
  template:
    metadata:
      labels:
        app: record-service
    spec:
      containers:
      - name: record-service
        image: adiprerepa/cachethrash-papa:latest
        env:
        - name: CACHE_SIZE
          value: "100"
        - name: DB_LATENCY_MS
          value: "100"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: record-service
spec:
  selector:
    app: record-service
  ports:
  - port: 80
    targetPort: 8080
